version: '3.9'
services:
   readme-551.user.mongo:
     image: mongo:4.4
     restart: always
     container_name: readme-551.user.mongo

     environment:
       MONGO_INITDB_ROOT_USERNAME: admin
       MONGO_INITDB_ROOT_PASSWORD: test
       MONGO_INITDB_DATABASE: readme-551.user.mongo

     ports:
       - ${MONGO_PORT}:27021

     volumes:
       - readme-551.mongo.user:/data/db

     healthcheck:
       test: echo 'db.runCommand("ping").ok' | mongosh localhost:27021/readme-551 --quiet
       interval: 10s
       timeout: 10s
       retries: 5

volumes:
   readme-551.mongo.user:
