###

# Create a new text blog
POST http://localhost:3333/api/blog HTTP/1.1
Content-Type: application/json

{
  "type": "text",
  "content": {
   "firstname": "Keks",
   "lastname": "Smith",
    "annotation": "cats",
    "content": "cute cats play together"
  },
  "author": "Adam Morgan",
  "tags": ["cats"]
}

###

# Login user by email and password
GET http://localhost:3333/api/blog/28f02d10-f8a6-4732-8e60-87203598bbb9 HTTP/1.1
Content-Type: application/json

###

# Change user password
PUT http://localhost:3333/api/blog/fb2c6401-a451-4bd0-b663-11cfa9ec6610 HTTP/1.1
Content-Type: application/json

{
  "postedDate": "2023-12-12",
  "status": "public",
  "content": {
    "name": "Cute cats - 2",
    "link": "https://www.youtube.com/watch?v=z3U0udLH974"
  },
  "tags": ["thebest", "fanny"]
}

###

# Change user password
DELETE http://localhost:3000/api/blog/cfd84542-6f3c-4a22-9295-e961a676352f HTTP/1.1
Content-Type: application/json

###
