 ###
# Create a new video blog
POST http://localhost:3000/api/blog HTTP/1.1
Content-Type: application/json

 {
   "type": "video",
   "content": {
     "name": "Длина которая больше 20",
     "link": "https://www.youtube.com/watch?v=y0sF5xhGreA"
   },
   "userId": "65a248fa590fc5abaf0d89ea",
   "tags": ["Thebest#"]
 }

 ###

###

# Create a new text blog
POST http://localhost:3000/api/blog HTTP/1.1
Content-Type: application/json

{
  "type": "text",
  "content": {
   "firstname": "Ivan",
   "lastname": "Rorn",
    "annotation": "cats",
    "content": "cute cats play together"
  },
  "author": "Ivan Dorn",
  "tags": ["cats"]
}

###

# Login user by email and password
GET http://localhost:3000/api/blog/dbb7474c-a115-4892-b309-fd594421d94e HTTP/1.1
Content-Type: application/json

###


 # Delete blog by id

DELETE http://localhost:3000/api/blog/f9dfff46-9bb2-42c1-a7ef-0614ecc01ccc HTTP/1.1
Content-Type: application/json

 ###

# Change user password
PUT http://localhost:3333/api/blog/с88d8b49d-d67e-423c-8830-322919876851 HTTP/1.1
Content-Type: application/json

{
  "postedDate": "2023-12-12",
  "status": "public",
  "content": {
    "name": "Cute cats - 2",
    "link": "https://www.youtube.com/watch?v=z3U0udLH974"
  },
  "tags": ["thebest", "fanny"]
}

###

# Create a new text blog
POST http://localhost:3000/api/blog HTTP/1.1
Content-Type: application/json

 {
   "type": "text",
   "content": {
     "name": "Cute cats and some more symbols for validate",
     "annotation": "Длина текста должна быть 50 символов как минимум, так что будем растягивать как можем",
     "content": "Длина текста должна быть 50 символов как минимум, так что будем растягивать как можем.И еще разок. Длина текста должна быть 50 символов как минимум, так что будем растягивать как можем"
   },
   "userId": "65a24913ebc68fe10750437a",
   "tags": ["cats"]
 }

 ###

# Change user password
DELETE http://localhost:3333/api/blog/88d8b49d-d67e-423c-8830-322919876851 HTTP/1.1
Content-Type: application/json

###

# Create a new video blog
POST http://localhost:3000/api/blog HTTP/1.1
Content-Type: application/json

 {
   "type": "video",
   "content": {
     "name": "Длина которая больше 20",
     "link": "https://www.youtube.com/watch?v=y0sF5xhGreA"
   },
   "userId": "65a248fa590fc5abaf0d89ea",
   "tags": ["Thebest#"]
 }

 ###


