# Get user by ID
 GET http://localhost:3000/api/auth/0a0ad1bb-c1b6-49b2-af63-b4717f1baa1b HTTP/1.1

###




# Create a new user
 POST http://localhost:3000/api/auth/register HTTP/1.1
 Content-Type: application/json

 {
   "email": "user@found.ru",
   "firstname": "Keks",
   "lastname": "Smith",
   "password": "123456"
 }

###


# Get user by ID
 GET http://localhost:3000/api/auth/0a0ad1bb-c1b6-49b2-af63-b4717f1baa1b HTTP/1.1

 ###

# Login user by email and password
 POST http://localhost:3000/api/auth/login HTTP/1.1
 Content-Type: application/json

 {
   "email": "user@notfound.local",
   "password": "123456"
 }

 ###
